export const SOURCE_FILES = [
  { path: "GNUmakefile", label: "GNUmakefile" },
  { path: "Makefile", label: "Makefile" },
  { path: "Package.swift", label: "Package.swift" },
  { path: "README.md", label: "README.md" },
  { path: "LICENSE", label: "LICENSE" },
  { path: "Tools/ois-filter.m", label: "ois-filter.m" },
  { path: "Source/include/OISRuntime.h", label: "OISRuntime.h" },
  { path: "Source/include/ODataIncrementalStore.h", label: "ODataIncrementalStore.h" },
  { path: "Source/ODataIncrementalStore.m", label: "ODataIncrementalStore.m" },
  { path: "Source/include/ODataPredicateTranslator.h", label: "ODataPredicateTranslator.h" },
  { path: "Source/ODataPredicateTranslator.m", label: "ODataPredicateTranslator.m" },
  { path: "Source/include/ODataQueryBuilder.h", label: "ODataQueryBuilder.h" },
  { path: "Source/ODataQueryBuilder.m", label: "ODataQueryBuilder.m" },
  { path: "Source/include/ODataClient.h", label: "ODataClient.h" },
  { path: "Source/ODataClient.m", label: "ODataClient.m" },
  { path: "Source/include/ODataPropertyMapper.h", label: "ODataPropertyMapper.h" },
  { path: "Source/ODataPropertyMapper.m", label: "ODataPropertyMapper.m" },
  { path: "Source/include/ODataConfiguration.h", label: "ODataConfiguration.h" },
  { path: "Source/ODataConfiguration.m", label: "ODataConfiguration.m" },
  { path: "Source/include/ODataResourceIdentifier.h", label: "ODataResourceIdentifier.h" },
  { path: "Source/ODataResourceIdentifier.m", label: "ODataResourceIdentifier.m" },
  { path: "Source/include/ODataError.h", label: "ODataError.h" },
  { path: "Source/ODataError.m", label: "ODataError.m" },
  { path: "Source/include/OISCoreData.h", label: "OISCoreData.h" },
  { path: "Source/include/OISCoreDataStub.h", label: "OISCoreDataStub.h" },
  { path: "Source/OISCoreDataStub.m", label: "OISCoreDataStub.m" },
] as const;
