export type SourceGroup = "library" | "tests" | "example";

export const SOURCE_FILES: { path: string; label: string; group: SourceGroup }[] = [
  { path: "GNUmakefile", label: "GNUmakefile", group: "library" },
  { path: "Makefile", label: "Makefile", group: "library" },
  { path: "Package.swift", label: "Package.swift", group: "library" },
  { path: "README.md", label: "README.md", group: "library" },
  { path: "LICENSE", label: "LICENSE", group: "library" },
  { path: "Tools/ois-filter.m", label: "ois-filter.m", group: "library" },
  { path: "Source/include/OISRuntime.h", label: "OISRuntime.h", group: "library" },
  { path: "Source/include/ODataIncrementalStore.h", label: "ODataIncrementalStore.h", group: "library" },
  { path: "Source/ODataIncrementalStore.m", label: "ODataIncrementalStore.m", group: "library" },
  { path: "Source/include/ODataPredicateTranslator.h", label: "ODataPredicateTranslator.h", group: "library" },
  { path: "Source/ODataPredicateTranslator.m", label: "ODataPredicateTranslator.m", group: "library" },
  { path: "Source/include/ODataQueryBuilder.h", label: "ODataQueryBuilder.h", group: "library" },
  { path: "Source/ODataQueryBuilder.m", label: "ODataQueryBuilder.m", group: "library" },
  { path: "Source/include/ODataClient.h", label: "ODataClient.h", group: "library" },
  { path: "Source/ODataClient.m", label: "ODataClient.m", group: "library" },
  { path: "Source/include/ODataPropertyMapper.h", label: "ODataPropertyMapper.h", group: "library" },
  { path: "Source/ODataPropertyMapper.m", label: "ODataPropertyMapper.m", group: "library" },
  { path: "Source/include/ODataConfiguration.h", label: "ODataConfiguration.h", group: "library" },
  { path: "Source/ODataConfiguration.m", label: "ODataConfiguration.m", group: "library" },
  { path: "Source/include/ODataResourceIdentifier.h", label: "ODataResourceIdentifier.h", group: "library" },
  { path: "Source/ODataResourceIdentifier.m", label: "ODataResourceIdentifier.m", group: "library" },
  { path: "Source/include/ODataError.h", label: "ODataError.h", group: "library" },
  { path: "Source/ODataError.m", label: "ODataError.m", group: "library" },
  { path: "Source/include/OISCoreData.h", label: "OISCoreData.h", group: "library" },
  { path: "Source/include/OISCoreDataStub.h", label: "OISCoreDataStub.h", group: "library" },
  { path: "Source/OISCoreDataStub.m", label: "OISCoreDataStub.m", group: "library" },
  { path: "Tests/GNUmakefile", label: "Tests/GNUmakefile", group: "tests" },
  { path: "Tests/README.md", label: "Tests/README.md", group: "tests" },
  { path: "Tests/ODataSnapshotTransport.h", label: "ODataSnapshotTransport.h", group: "tests" },
  { path: "Tests/ODataSnapshotTransport.m", label: "ODataSnapshotTransport.m", group: "tests" },
  { path: "Tests/OISTestSupport.h", label: "OISTestSupport.h", group: "tests" },
  { path: "Tests/OISTestSupport.m", label: "OISTestSupport.m", group: "tests" },
  { path: "Tests/ODataPredicateTranslatorTests.m", label: "ODataPredicateTranslatorTests.m", group: "tests" },
  { path: "Tests/ODataQueryBuilderTests.m", label: "ODataQueryBuilderTests.m", group: "tests" },
  { path: "Tests/ODataResourceIdentifierTests.m", label: "ODataResourceIdentifierTests.m", group: "tests" },
  { path: "Tests/ODataSnapshotStoreTests.m", label: "ODataSnapshotStoreTests.m", group: "tests" },
  { path: "Tests/Snapshots/index.json", label: "Snapshots/index.json", group: "tests" },
  { path: "Examples/Catalog/README.md", label: "Catalog/README.md", group: "example" },
  { path: "Examples/Catalog/GNUmakefile", label: "Catalog/GNUmakefile", group: "example" },
  { path: "Examples/Catalog/main.m", label: "Catalog/main.m", group: "example" },
  { path: "Examples/Catalog/CatalogController.m", label: "CatalogController.m", group: "example" },
  { path: "Examples/Catalog/CatalogModel.m", label: "CatalogModel.m", group: "example" },
];
