/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as SourceRouteImport } from './routes/source'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as OdataIndexRouteImport } from './routes/odata.index'
import { Route as OdataSplatRouteImport } from './routes/odata.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const OdataIndexRoute = OdataIndexRouteImport.update({
  id: '/odata/',
  path: '/odata/',
  getParentRoute: () => rootRouteImport,
} as any)
const OdataSplatRoute = OdataSplatRouteImport.update({
  id: '/odata/$',
  path: '/odata/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/license': typeof LicenseRoute
  '/source': typeof SourceRoute
  '/tests': typeof TestsRoute
  '/workbench': typeof WorkbenchRoute
  '/odata/$': typeof OdataSplatRoute
  '/odata/': typeof OdataIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/license': typeof LicenseRoute
  '/source': typeof SourceRoute
  '/tests': typeof TestsRoute
  '/workbench': typeof WorkbenchRoute
  '/odata/$': typeof OdataSplatRoute
  '/odata': typeof OdataIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/license': typeof LicenseRoute
  '/source': typeof SourceRoute
  '/tests': typeof TestsRoute
  '/workbench': typeof WorkbenchRoute
  '/odata/$': typeof OdataSplatRoute
  '/odata/': typeof OdataIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/license'
    | '/source'
    | '/tests'
    | '/workbench'
    | '/odata/$'
    | '/odata/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/license'
    | '/source'
    | '/tests'
    | '/workbench'
    | '/odata/$'
    | '/odata'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/license'
    | '/source'
    | '/tests'
    | '/workbench'
    | '/odata/$'
    | '/odata/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  LicenseRoute: typeof LicenseRoute
  SourceRoute: typeof SourceRoute
  TestsRoute: typeof TestsRoute
  WorkbenchRoute: typeof WorkbenchRoute
  OdataSplatRoute: typeof OdataSplatRoute
  OdataIndexRoute: typeof OdataIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odata/': {
      id: '/odata/'
      path: '/odata'
      fullPath: '/odata/'
      preLoaderRoute: typeof OdataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odata/$': {
      id: '/odata/$'
      path: '/odata/$'
      fullPath: '/odata/$'
      preLoaderRoute: typeof OdataSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  LicenseRoute: LicenseRoute,
  SourceRoute: SourceRoute,
  TestsRoute: TestsRoute,
  WorkbenchRoute: WorkbenchRoute,
  OdataSplatRoute: OdataSplatRoute,
  OdataIndexRoute: OdataIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
